# Generated by Django 2.0.7 on 2018-08-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
