# Generated by Django 2.0.7 on 2018-08-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_details',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
